src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=BienRepository::class)
 * @Vich\Uploadable
 */
class Bien
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_bien;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="biens_categorie")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="biens_user")
     */
    private $proprietaire;

    /**
     * @ORM\OneToMany(targetEntity=Pret::class, mappedBy="bien_pret")
     */
    private $pret_bien;

    public function __construct()
    {
        $this->pret_bien = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomBien(): ?string
    {
        return $this->nom_bien;
    }

    public function setNomBien(string $nom_bien): self
    {
        $this->nom_bien = $nom_bien;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getproprietaire(): ?User
    {
        return $this->proprietaire;
    }

    public function setproprietaire(?User $proprietaire): self
    {
        $this->proprietaire = $proprietaire;

        return $this;
    }


     public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function __toString()
    {
        return $this->nom_bien;
    }

    /**
     * @return Collection|Pret[]
     */
    public function getPretBien(): Collection
    {
        return $this->pret_bien;
    }

    public function addPretBien(Pret $pretBien): self
    {
        if (!$this->pret_bien->contains($pretBien)) {
            $this->pret_bien[] = $pretBien;
            $pretBien->setBienPret($this);
        }

        return $this;
    }

    public function removePretBien(Pret $pretBien): self
    {
        if ($this->pret_bien->contains($pretBien)) {
            $this->pret_bien->removeElement($pretBien);
            // set the owning side to null (unless already changed)
            if ($pretBien->getBienPret() === $this) {
                $pretBien->setBienPret(null);
            }
        }

        return $this;
    }
   
}

src/Entity/Pret.php
<?php

namespace App\Entity;



use Doctrine\ORM\Mapping as ORM;
use App\Repository\PretRepository;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PretRepository::class)
 */
class Pret
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pret_user")
     */
    private $user;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual("today")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual(propertyPath="dateDebut")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="integer")
     */
    private $points_pret;

    /**
     * @ORM\ManyToOne(targetEntity=Bien::class, inversedBy="pret_bien")
     */
    private $bien_pret;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPointsPret(): ?int
    {
        return $this->points_pret;
    }

    public function setPointsPret(int $points_pret): self
    {
        $this->points_pret = $points_pret;

        return $this;
    }

    public function getBienPret(): ?Bien
    {
        return $this->bien_pret;
    }

    public function setBienPret(?Bien $bien_pret): self
    {
        $this->bien_pret = $bien_pret;

        return $this;
    }

    public function isIncluded($date): bool
    {
        return $date >= $this->date_debut && $date <= $this->date_fin;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;  


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 *  fields={"email"},
 *  message="cet email est déjà utilisé"
 * )s
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="integer")
     */
    private $points;

    /**
     * @ORM\OneToMany(targetEntity=Bien::class, mappedBy="proprietaire")
     */
    private $biens_user;

    /**
     * @ORM\OneToMany(targetEntity=Pret::class, mappedBy="user")
     */
    private $pret_user;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function __construct()
    {
        $this->biens_user = new ArrayCollection();
        $this->pret_user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function getUsername(): ?string
    {
        return $this->pseudo;
    }


    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPoints(): ?int
    {
        return $this->points;
    }

    public function setPoints(int $points): self
    {
        $this->points = $points;

        return $this;
    }

    /**
     * @return Collection|Bien[]
     */
    public function getBiensUser(): Collection
    {
        return $this->biens_user;
    }

    public function addBiensUser(Bien $biensUser): self
    {
        if (!$this->biens_user->contains($biensUser)) {
            $this->biens_user[] = $biensUser;
            $biensUser->setProprietaire($this);
        }

        return $this;
    }

    public function removeBiensUser(Bien $biensUser): self
    {
        if ($this->biens_user->contains($biensUser)) {
            $this->biens_user->removeElement($biensUser);
            // set the owning side to null (unless already changed)
            if ($biensUser->getProprietaire() === $this) {
                $biensUser->setProprietaire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Pret[]
     */
    public function getPretUser(): Collection
    {
        return $this->pret_user;
    }

    public function addPretUser(Pret $pretUser): self
    {
        if (!$this->pret_user->contains($pretUser)) {
            $this->pret_user[] = $pretUser;
            $pretUser->setUser($this);
        }

        return $this;
    }

    public function removePretUser(Pret $pretUser): self
    {
        if ($this->pret_user->contains($pretUser)) {
            $this->pret_user->removeElement($pretUser);
            // set the owning side to null (unless already changed)
            if ($pretUser->getUser() === $this) {
                $pretUser->setUser(null);
            }
        }

        return $this;
    }

    public function eraseCredentials()
    {
        
    }

    public function getSalt()
    {
        
    }


    public function __toString()
    {
        return $this->pseudo;
    }

    public function getRoles(): ?array
    {
        if(empty($this->roles)){
            return ['ROLE_USER'];
        }
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles[] = $roles;

        return $this;
    }

    public function addRoles($roles)
    {
        $this->roles[] = $roles;
    }
    

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Bien;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class UserController extends AbstractController
{
    /**
     * @Route("profile/moncompte", name="user")
     */
    public function show()
    {
        $user = $this->getUser();
        $biensUser = $user->getBiensUser();
        $pretsUser = $user->getPretUser();
        //$mesEmprunts = $emprunts->getBienPret();
        $datedujour = new DateTime();

        return $this->render('user/user.html.twig', [
            'user' => $user,
            'biensUser' => $biensUser,
            'pretsUser' => $pretsUser,
            'date' => $datedujour,
       ]);
    }


     /**
     * @Route("profile/delete/{id}", name="delete")
     * param int $id
     * @return Response
     */
    public function delete(Bien $bien):Response
    {
        
        $em = $this->getDoctrine()->getManager();
        $em->remove($bien);
        
        $em->flush();

        $this->addFlash('success', 'Annonce supprimée');

        return $this->redirectToRoute('index'); 
    }
}

templates/user/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Compte{% endblock %}

{% block body %}
<div class="container">
    <h2 class="text-center my-5">Mon compte</h2>
        <div class="row text-center d-flex justify-content-center align-items-center my-4 description">  

            <div class='col-sm-12 col-md-6 col-lg-6 my-3'>
                <div><i class="fas fa-user-circle fa-5x mt-2"></i></div>
                <div class="mt-3">Mon pseudo : {{user.pseudo}}</div>
                {% if user.points >= 200 %}
                <div class="mt-3"> Super Prêteur <i class="fas fa-medal"></i></div>
                {% endif %}
            </div>

            <div class='col-sm-12 col-md-6 col-lg-6 my-3'>
                <div><i class="fas fa-envelope mr-2"></i>Mon email : {{user.email}}</div>
                <div class="mt-2"><i class="fas fa-star mr-2"></i>Mes points : {{user.points}} points</div>
                <div class="mt-2"><a class="lien" href="/profile/ajout"><i class="fas fa-upload mr-2"></i>Ajouter un bien </a></div>
            
            </div>
    <hr>
        </div>

    <h2 class="text-center my-5">Mes annonces</h2>
        <div class="row text-center d-flex justify-content-center align-items-center my-4"> 
    
    {% for biens in biensUser %}
        <div class="col-sm-12 col-md-12 col-lg-4 my-3">
            {% if biens.pretBien %}
            {% for prets in biens.pretBien %}
            
            {% if "now"|date('d/m/Y') >= prets.dateDebut|date('d/m/Y') or "now"|date('d/m/Y') <= prets.dateFin|date('d/m/Y')  %}
            <div class="badge pret"> 
            emprunté par {{prets.user}} <br>
            jusqu'au {{prets.dateFin|date('d/m/Y')}}
            </div>
            {% endif %}
            
            {% else %}
            

            {% endfor %}
            {% endif %}
            <img src="/uploads/{{biens.image}}" class=" img-thumbnail card-img-top" alt="">
            <div class="mt-2">{{biens.nomBien}}</div>
            <div class="mt-2"><a href="{{ path ('delete', {'id':biens.id}) }}" type="button" class="btn btn-outline-dark">Supprimer</button></a></div>
        </div>
        
    {% endfor %}
    
    </div>

    <h2 class="text-center my-5">Mes Emprunts</h2>
        <div class="row text-center d-flex justify-content-center align-items-center my-4 engagements">
        
{% for prets in pretsUser %}

<div class="col-12 my-3">
    <div class="my-3 font-weight-bold">
    <a href="/{{prets.bienPret.id}}" class="lien">{{prets.bienPret}}</a>
    </div>
    <div>

    {% if prets.dateDebut.format('d/m/Y') > "now"|date('d/m/Y')%}
    <span class="badge">A venir</span>
    {% endif %}
    {% if prets.dateFin.format('d/m/Y') < "now"|date('d/m/Y')%}
    <span class="badge">Terminé</span>
    {% endif %}
    </div>
    <div class="my-3">
    Emprunté du 
    {{prets.dateDebut.format('d/m/Y')}}
    au
    {{prets.dateFin.format('d/m/Y')}}
    </div>
    <hr class="w-25">
    
</div>

{% endfor %}
</div>
</div>
{% endblock %}